apiVersion: v1
kind: Pod
metadata:
 name: time-check
spec:
 containers:
 - name: time-check
   image: busybox:latest
   command: ["/bin/sh", "-c"]
   args: ["while true; do date; sleep $TIME_FREQ;done > /opt/data/time/time-check.log"]
   volumeMounts:
   - name: log-volume
     mountPath: /opt/data/time
   env:
   - name: TIME_FREQ
     valueFrom:
      configMapKeyRef:
        name: time-config
        key: TIME_FREQ
 volumes:
 - name: log-volume
   emptyDir: {}
