apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
   db: mariadb
  name: iron-db-deployment-devops
  namespace: iron-namespace-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mariadb
  template:
    metadata:
      labels:
        db: mariadb
    spec:
     containers:
     - name: iron-db-container-devops
       image: kodekloud/irondb:2.0
       env:
       - name: MYSQL_DATABASE
         value: database_host
       - name: MYSQL_ROOT_PASSWORD
         value: password
       - name: MYSQL_PASSWORD
         value: password
       - name: MYSQL_USER
         value: dba_user
       volumeMounts:
       - name: db
         mountPath: /var/lib/mysql
     volumes:
     - name: db
       emptyDir: {}
