apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: iron-gallery
  name: iron-gallery-service-devops
  namespace: iron-namespace-devops
spec:
  ports:
  - nodePort: 32678
    protocol: TCP
    targetPort: 80
    port: 80
  selector:
    run: iron-gallery
  type: NodePort
status:
  loadBalancer: {}
